compte/urls.py
from django.urls import path 

from . import views

app_name = 'compte'
urlpatterns = [
    path('register/', views.user_registration_view, name='register'),
    path('login/', views.user_login_view, name='login'),
    path('password-reset/<uidb64>/<token>/', views.activate_account_view, name='password_reset'),
    path('logout/', views.logout_view, name='logout'),
]

cours/urls.py
from django.urls import path 
from .views import CourseListView, CourseDetailView,\
CourseCreateView, CouseUpdateView, CourseDeleteView,\
    FCourseListView, FCoursDetailView, FCourseCreateView, FCourseUpdateView, FCourseDeleteView, test_task, test_task_result
app_name = 'cours'
urlpatterns = [
    # path('list/', CourseListView.as_view(), name='cours-list'),
    path('list/', FCourseListView.as_view(), name='cours-list'),
    # path('detail/<int:pk>/', CourseDetailView.as_view(), name='cours-detail'),
    path('detail/<int:pk>/', FCoursDetailView.as_view(), name='cours-detail'),
    # path('create/', CourseCreateView.as_view(), name='cours-create'),
    path('create/', FCourseCreateView.as_view(), name='cours-create'),
    # path('update/<int:pk>/', CouseUpdateView.as_view(), name='cours-update'),
    path('update/<int:pk>/', FCourseUpdateView.as_view(), name='cours-update'),
    # path('delete/<int:pk>/', CourseDeleteView.as_view(), name='cours-delete'),
    path('delete/<int:pk>/', FCourseDeleteView.as_view(), name='cours-delete'),
    path('test/', test_task, name='test-task'),
    path('test/<str:task_id>/', test_task_result, name='test_task_result')
]

essaiedjango/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('produits.urls')),
    path('cours/', include('cours.urls')),
    path('tache/', include('tache.urls')),
    path('compte/', include('compte.urls')),
   
]

pages/urls.py
from django.urls import path 
from .views import *

app_name = 'pages'

urlpatterns = [
    path('', home_view, name='home'), # path,url 
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('product_deta/<int:my_id>/', product_detail_view, name='product_detail'),
    path('product_create/', product_create_view, name='product_create'),
    path('product_delete/<int:my_id>/', product_delete_view, name='product_delete'),
    path('product_list/', product_list_view, name='product_list'),
    
]

templates/about.html
{% extends 'base.html' %}
{% block title %} about {% endblock title %}

{% block content %}
{% comment %} <h1> about page </h1> {% endcomment %}

<h3> {{ title|capfirst|upper|cut:'U' }} </h3>

{% for nombre in liste_numbre %}
<li> {{ nombre|add:100 }} </li>
{% endfor %}

<h1>{{html|striptags  }}</h1>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script defer src="{% static 'js/base.js' %}"></script>

    {% block css %} {% endblock css %}
</head>
<body>

   
    <nav>
        <ul>
            <li><a href="">Home</a></li>
            
            {% if user.is_authenticated %}
            <li><a href="{% url 'compte:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'compte:login' %}">Login</a></li>
            <li><a href="{% url 'compte:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>

    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}

    {% endif %}
    
   



    {% block content %}

    {% endblock content %}



    <footer>
        <p>Footer</p>   

    </footer>    
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %} contact {% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<h1>Contact page </h1>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} home  {% endblock title %}
{% block css %} 

{% endblock css %}

{% block content %}
{% include 'navbar.html' %}

<h1> home page </h1>

<img src="{% static 'image/Pictures/APIs.png' %}" alt="image" width="100%" height="500px" >




{% if liste  %}
<center>
    {% for i in liste %}
    <li>
       {{ forloop.counter }} - {{i}}
    </li>
    {% empty %}
    <li> liste vide </li>
    {% endfor %}
</center>

{% endif %}

{% if request.user.is_authenticated %}
<h1> hello {{ request.user.username }} </h1>

{% else %} 

<h1> hello guest </h1>

{% endif %}



{% include 'section_home.html' %}
<h1> home page </h1>
{% endblock content %}

templates/navbar.html
<nav>
    <ul>
        </li><a href="{% url 'pages:home' %}">Home</a></li>
        <li><a href="{% url 'pages:about' %}">About</a></li>
        <li><a href="{% url 'pages:contact' %}">Contact</a></li>
    </ul>
</nav>

templates/section_home.html
<section>
    <h2> welcome to my website</h2>
    <p> this is a website that i made for my school project</p>
</section>
<section>
    <h2> about me</h2>
    <p> my name is joshua and i am a student at the university of the west indies</p>
</section>
<section>
    <h2> about this website</h2>
    <p> this website is a website that i made for my school project</p>     
</section>