cours/urls.py
from django.urls import path 
from .views import CourseListView, CourseDetailView,\
CourseCreateView, CouseUpdateView, CourseDeleteView,\
    FCourseListView, FCoursDetailView, FCourseCreateView, FCourseUpdateView, FCourseDeleteView, test_task, test_task_result
app_name = 'cours'
urlpatterns = [
    # path('list/', CourseListView.as_view(), name='cours-list'),
    path('list/', FCourseListView.as_view(), name='cours-list'),
    # path('detail/<int:pk>/', CourseDetailView.as_view(), name='cours-detail'),
    path('detail/<int:pk>/', FCoursDetailView.as_view(), name='cours-detail'),
    # path('create/', CourseCreateView.as_view(), name='cours-create'),
    path('create/', FCourseCreateView.as_view(), name='cours-create'),
    # path('update/<int:pk>/', CouseUpdateView.as_view(), name='cours-update'),
    path('update/<int:pk>/', FCourseUpdateView.as_view(), name='cours-update'),
    # path('delete/<int:pk>/', CourseDeleteView.as_view(), name='cours-delete'),
    path('delete/<int:pk>/', FCourseDeleteView.as_view(), name='cours-delete'),
    path('test/', test_task, name='test-task'),
    path('test/<str:task_id>/', test_task_result, name='test_task_result')
]

essaiedjango/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('produits.urls')),
    path('cours/', include('cours.urls')),
    path('tache/', include('tache.urls')),
    path('compte/', include('compte.urls')),
   
]

cours/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Cours(models.Model):
    nom = models.CharField(max_length=100)
    description = models.TextField()

    
    
    def get_absolute_url(self):
        return reverse("cours-detail", kwargs={"pk": self.pk})


class ImageCours(models.Model):
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE) 
    image = models.ImageField(upload_to='media')   

cours/forms.py
from django import forms 
from .models import Cours

class CoursForm(forms.ModelForm):
    
    class Meta:
        model = Cours 
        
        fields = [
            'nom',
            'description',
        ]
        
    # def clean_nom(self, *args, **kwargs):
    #     nom = self.cleaned_data.get("nom")
    #     if nom != "Francais":
    #         raise forms.ValidationError("ce cours n'est pas autorisé")
    #     return nom    

cours/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic import (
    ListView, 
    DetailView, 
    UpdateView, 
    CreateView, 
    DeleteView
)
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from .models import Cours
from .forms import CoursForm

from compte.permissions import group_required, role_required, GroupRequiredMixin, RoleRequiredMixin
# class based view 

from django.views import View 

class CoursViewMixin(object):
    model = Cours 
    def get_object(self):
        pk = self.kwargs.get('pk')
        obj = None 
        if pk is not None:
            obj = get_object_or_404(self.model, pk=pk)
        return obj


class FCourseListView(LoginRequiredMixin, RoleRequiredMixin,  View):
    
   
    
    roles = ['is_professor']
    
    template_name = 'cours/cours_lis.html'
    def get(self, request,  *args, **kwargs):
        queryset = Cours.objects.all()
        context = {
            'object_list': queryset
        }
        return render(request, self.template_name, context)

class FCoursDetailView(CoursViewMixin, View):
    template_name = 'cours/cours_detail.html'
    
    def get(self, request, pk=None, *args, **kwargs):
        context = {
           'object': self.get_object()
         }
        return render(request, self.template_name, context)
    
    def post(self, request):
        pass 
    

class FCourseCreateView(View):
    template_name = 'cours/cours_create.html'
    form = CoursForm()
    context = {
            'form': form
        }
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
    
    def post(self, request, *args, **kwargs):
        form = CoursForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cours:cours-list')
        return render(request, self.template_name, self.context)
    
    
class FCourseUpdateView(CoursViewMixin, View):
    template_name='cours/cours_update.html'
    
    def get(self, request, pk=None, *args, **kwargs):
        context = {
            'form': CoursForm(instance=self.get_object())
        }
        return render(request, self.template_name, context) 
    
    
    def post(self, request, *args, **kwargs):
        form = CoursForm(request.POST, instance=self.get_object())
        if form.is_valid():
            form.save()
            return redirect('cours:cours-list')
        return render(request, self.template_name, {'form': form})  
        

class FCourseDeleteView(CoursViewMixin, View):
    template_name = 'cours/cours_delete.html'   
    
    def get(self, request, pk=None, *args, **kwargs):
        context = {
            'object': self.get_object()
        }
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj is not None:
            obj.delete()
            return redirect('cours:cours-list')
        return render(request, self.template_name, {'object': obj})
    
    
class CourseListView(ListView): # <modelname>_list.html
    template_name ='cours/cours_lis.html'
    queryset = Cours.objects.all()
    

class CourseDetailView(DetailView): # <modelname>_detail.html
    template_name ='cours/cours_detail.html'
    queryset = Cours.objects.all()    

class CourseCreateView(CreateView):
    form_class = CoursForm
    template_name = 'cours/cours_create.html'
    queryset = Cours.objects.all() 
    
    def form_valid(self, form):
        nom = form.cleaned_data.get('nom')
        if nom != "Francais":
            form.add_error("nom", "ce cours n'est pas autorisé validation vue")
            return self.form_invalid(form)
        return super().form_valid(form)
    

class CouseUpdateView(UpdateView):
    form_class = CoursForm
    template_name = 'cours/cours_update.html'
    queryset = Cours.objects.all()    
    

class CourseDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'cours.delete_cours'
    template_name = 'cours/cours_delete.html'
    queryset = Cours.objects.all() 
    
    
    def get_success_url(self):
        return reverse("cours:cours-list")

@role_required(['is_professor'])

@group_required('professor')
def list_view(request):
    queryset = Cours.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, 'cours/cours_lis.html', context)       


from .tasks import add, create_cours_for_testing

def test_task(request):

    result = create_cours_for_testing.delay()

    return render(request, 'cours/test_task.html', {'result': result})



def test_task_result(request, task_id):
    result = create_cours_for_testing.AsyncResult(task_id)

    if result.ready():
        return render(request, 'cours/test_task_result.html', {'result': result.result})
    return render(request, 'cours/test_task_result.html', {'result': "result not ready yet"})

cours/templates/cours/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>formation django </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    

    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

cours/templates/cours/cours_create.html
{% extends 'cours/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-md-12">

                <h1 class="text-center display-4"> creer un cours </h1>



            <form method="post" class="form">
                {% csrf_token %}

                {% bootstrap_form form %}

                {% bootstrap_button button_type="submit" content="Creer" %}
                {% bootstrap_button button_type="reset" content="Annuler" %}
            </form>

        </div>

</div>
{% endblock %}

cours/templates/cours/cours_delete.html
<h1> supprimer un cours </h1>

<p> Voulez vous vraiment supprimer le cours {{ object.nom }} ? </p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Oui, je veux supprimer ce cours" />
</form>

cours/templates/cours/cours_detail.html
<h1> Cours Detail </h1>

<p> Nom: {{ object.nom }} </p>
<p> description: {{ object.description }} </p>

cours/templates/cours/cours_lis.html
{% extends 'cours/base.html' %}
{% load custom_filters %}

{% block content %}

<h1 class='text-center '> cours liste </h1>

<div class='container'>

    {% for cours in object_list %}

    <p> {{ cours.nom|upper_case  }} : {{50|multiply:10}} </p>

<hr>
{% endfor %}

</div>    
{% endblock %}

cours/templates/cours/cours_update.html
<h1> modifier un cours </h1>


<form method="post"> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="modifier">
</form>

cours/templates/cours/test_task.html
<p> voici le id de la tache {{ result}} </p>
<a href="{% url 'cours:test_task_result' task_id=result %}"> voir le resultat </a>
```

cours/templates/cours/test_task_result.html
<p> {{result}} </p>